### ISSUE TITLE
sptk::FrequencyTransform is quite slow

### ISSUE THREAD

**Issue by highfly22** [sp-nitech/SPTK#16]
The function freqt is computed by dynamic programming. But the recursion implementation cannot be auto-vectorized. The manual says that  "the above recursion can be represented as a linear transformation".

How to express general term formula for this  frequency-warped sequence?

**Comment by takenori-y** [comment]
It is hard to fully describe the transformation matrix with mathematical formulation. But the PyTorch version precomputes the transformation matrix. I hope this can help you.
https://github.com/sp-nitech/diffsptk/blob/260cfdf465f8cfd9430d33406a89fd19a9f61388/diffsptk/core/freqt.py#L52-L61

**Comment by highfly22** [comment]
Thanks. You save my day. 
I have struggle with this function for a week.
