### ISSUE TITLE
PitchExtractionByRapt::Get is not concurrency safe. Can you provide a concurrency safe version?

### ISSUE THREAD

**Issue by hankewei** [sp-nitech/SPTK#19]
**PitchExtractionByRapt::Get** is not concurrency safe，because **init_ dp_ f0** and **dp_f0** use a large number of global variables. Can you provide a concurrency safe version?

**Comment by takenori-y** [comment]
Thank you for your report. Let me check.

**Comment by takenori-y** [comment]
I pushed away the static variables to a single buffer. Can you try #20 ?

**Comment by takenori-y** [comment]
@hankewei 
I have updated #20 and checked the thread safety. If you have a still problem, please let me know.
