### ISSUE TITLE
Trying to use SPTK's PitchExtraction inside a real-time-enviorment

### ISSUE THREAD

**Issue by vackva** [sp-nitech/SPTK#39]
I am experiencing difficulties when trying to utilize the SPTK library for pitch extraction within a real-time environment (JUCE framework). Despite attempting various algorithms (kRapt, kSwipe, kReaper, kDio, kHarvest)  provided by the library, I have not been able to obtain the expected output. 

Most of the algorithms report successful execution (IsValid() and Run()), but the resulting pitch values are either nonexistent or consistently zero. 

To provide more context, I am employing the SPTK library within the prepareToPlay and processBlock functions of my audio plugin. Here is a brief overview of their functionality:

- `prepareToPlay` function:
    - This function is called before audio playback starts and is responsible for any necessary pre-playback initialization.
    - Expected values: sampleRate = 48000, samplesPerBlock = 480

- `processBlock` function:
    - This function is called repeatedly during audio processing and performs the actual pitch extraction on the audio buffer.

Here the relevant code snippets:

**header-File:**
```
    std::unique_ptr<sptk::PitchExtraction> pitchExtraction;
    std::vector<double> doubleBuffer;
```

**cpp-File:**
```
void prepareToPlay(double sampleRate, int samplesPerBlock)
{
doubleBuffer.resize(samplesPerBlock);

    pitchExtraction = std::make_unique<sptk::PitchExtraction>(samplesPerBlock, sampleRate, 60.0, 240.0, 0.0, sptk::PitchExtraction::kRapt);
}


void processBlock(juce::AudioBuffer<float>& buffer, juce::MidiBuffer&)
{
    // Other code...
    doubleBuffer.clear();

    // Converting audio buffer to double buffer
    auto read = buffer.getReadPointer(0);
    for (int sample = 0; sample < buffer.getNumSamples(); ++sample) {
        doubleBuffer.push_back(static_cast<double>(read[sample]));
    }

    // Pitch extraction
    std::vector<double> f0;
    auto success = pitchExtraction->Run(doubleBuffer, &f0, nullptr, nullptr);

    std::cout << "success: " << success << std::endl;

    for (double value : f0) {
        std::cout << "value: " << value << std::endl;
    }
}

```

Am I doing something wrong with the implementation? 
Does the raw audio need to be pre-processed to calculate f0?

I have also studied the file [pitch.cc](https://github.com/sp-nitech/SPTK/blob/master/src/main/pitch.cc) and followed your implementation with no success. I have also tried using a larger buffer (e.g. 5 seconds of audio) with no success.

**Comment by takenori-y** [comment]
The implemented algorithms are not suitable for online pitch extraction as they usually use long term information. I would not recommend using them even if you use a large buffer. It is computationally expensive. I know that YIN can extract pitch in an online manner.

Your usage seems to be correct, but I am not sure. Perhaps increasing the amplitude of the raw audio might change something.

Anyway, I recommend using other approaches for online pitch extraction.

**Comment by vackva** [comment]
Currently, I am using the SPTK library in a prototype to evaluate its functionality. Although the algorithms are not ideal for continuous real-time processing, my intention is to analyze audio data periodically in a separate thread for a few seconds at a time. Real-time constraints are not as critical in this scenario. But if the algorithms need long term information, its defently not the right library for my purpose.

I tried increasing the gain (+15dB) of the raw audio, but it didn't resolve the issue

Thank you for your help!

**Comment by takenori-y** [comment]
Thank you for your reply! We understand your situation.

I hope everything goes well.
