### ISSUE TITLE
can this project support windows?

### ISSUE THREAD

**Issue by suziW** [sp-nitech/SPTK#5]
it would be awesome if this project support windows.

**Comment by takenori-y** [comment]
We are trying to write CMakeLists.txt to support windows, but I'm not sure when it is finished.

**Comment by suziW** [comment]
> We are trying to write CMakeLists.txt to support windows, but I'm not sure when it is finished.

Did you encounter any problem? I will try to write a CMakeLists.txt too

**Comment by takenori-y** [comment]
We did not spend much time on that. One concern is that windows cannot use `getopt` in `unistd.h`. If you provide us any thoughts or a prototype CMakeLists.txt, it's great.

**Comment by takenori-y** [comment]
I found a nice [repository](https://github.com/katahiromz/getoptwin). The concern may be resolved.

**Comment by takenori-y** [comment]
@suziW
I made a branch #6. If you have any problem, please let me know.
